/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entities.ThiSinh;
import java.awt.Font;
import java.awt.event.*;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import utilities.ui.Ui;

public class QuanLyDiemView extends javax.swing.JPanel {
    List<ThiSinh> _thiSinh;

    /**
     * Creates new form QuanLyDiemView
     */
    public QuanLyDiemView() {
        initComponents();
        Ui.updateComboBoxAll(thF, new String[]{"KHTN", "KHXH"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new JLabel();
        timKiemField = new JTextField();
        scrollBar = new JScrollPane();
        table = new JTable();
        SBDLabel = new JLabel();
        findB = new JButton();
        monB = new JComboBox<>();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel11 = new JLabel();
        thF = new JComboBox<>();
        bothB = new JRadioButton();
        namB = new JRadioButton();
        nuB = new JRadioButton();
        exportFB = new JButton();
        sortBtn = new JButton();
        maxF = new JSpinner();
        minF = new JSpinner();
        resetB = new JButton();

        addComponentListener(new ComponentAdapter() {
            public void componentResized(ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new AbsoluteLayout());

        title1.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        title1.setText("QUẢN LÍ ĐIỂM THI ĐẠI HỌC");
        add(title1, new AbsoluteConstraints(530, 20, 330, -1));

        timKiemField.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        add(timKiemField, new AbsoluteConstraints(540, 110, 270, 30));

        table.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "SBD", "Họ và tên", "Giới tính", "Ngày sinh", "Tỉnh", "Trường", "SĐT", "Khối tổ hợp", "Toán", "Ngữ Văn", "Ngoại ngữ", "Môn 1", "Môn 2", "Môn 3"
            }
        ) {
            Class[] types = new Class [] {
                Object.class, String.class, String.class, Object.class, String.class, String.class, String.class, String.class, String.class, Double.class, Double.class, Double.class, Double.class, Double.class, Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRequestFocusEnabled(false);
        table.setRowHeight(25);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        scrollBar.setViewportView(table);

        add(scrollBar, new AbsoluteConstraints(30, 160, 1240, 480));

        SBDLabel.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        SBDLabel.setText("-");
        add(SBDLabel, new AbsoluteConstraints(420, 110, 10, 30));

        findB.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        findB.setText("Tìm");
        findB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                findBActionPerformed(evt);
            }
        });
        add(findB, new AbsoluteConstraints(1040, 100, 100, -1));

        monB.setModel(new DefaultComboBoxModel<>(new String[] { "Toan", "Van", "Anh", "Mon1", "Mon2", "Mon3" }));
        add(monB, new AbsoluteConstraints(170, 110, 160, 30));

        jLabel2.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cao nhất");
        add(jLabel2, new AbsoluteConstraints(440, 90, 70, -1));

        jLabel3.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Lọc theo từ khóa");
        add(jLabel3, new AbsoluteConstraints(540, 90, 210, -1));

        jLabel4.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tìm kiếm");
        add(jLabel4, new AbsoluteConstraints(30, 60, 200, -1));

        jLabel5.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Thấp nhất");
        add(jLabel5, new AbsoluteConstraints(340, 90, 70, -1));

        jLabel6.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tổ hợp");
        add(jLabel6, new AbsoluteConstraints(30, 90, 70, -1));

        jLabel7.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Môn");
        add(jLabel7, new AbsoluteConstraints(170, 90, 70, -1));

        jLabel11.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Lọc theo giới tính");
        add(jLabel11, new AbsoluteConstraints(830, 90, 160, -1));

        thF.setModel(new DefaultComboBoxModel<>(new String[] { "Toan", "Van", "Anh", "Mon1", "Mon2", "Mon3" }));
        thF.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                thFItemStateChanged(evt);
            }
        });
        add(thF, new AbsoluteConstraints(30, 110, 130, 30));

        bothB.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        bothB.setText("Cả 2");
        bothB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                bothBActionPerformed(evt);
            }
        });
        add(bothB, new AbsoluteConstraints(960, 110, -1, -1));

        namB.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        namB.setText("Nam");
        namB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                namBActionPerformed(evt);
            }
        });
        add(namB, new AbsoluteConstraints(830, 110, -1, -1));

        nuB.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        nuB.setText("Nữ");
        nuB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                nuBActionPerformed(evt);
            }
        });
        add(nuB, new AbsoluteConstraints(900, 110, -1, -1));

        exportFB.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        exportFB.setText("Xuất tệp tin");
        exportFB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                exportFBActionPerformed(evt);
            }
        });
        add(exportFB, new AbsoluteConstraints(260, 650, 210, -1));

        sortBtn.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        sortBtn.setText("Sắp xếp theo SBD");
        sortBtn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });
        add(sortBtn, new AbsoluteConstraints(30, 650, 210, -1));

        maxF.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        maxF.setModel(new SpinnerNumberModel(10.0d, 0.0d, 10.0d, 0.5d));
        add(maxF, new AbsoluteConstraints(440, 110, 70, -1));

        minF.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        minF.setModel(new SpinnerNumberModel(0.0d, 0.0d, 10.0d, 0.5d));
        add(minF, new AbsoluteConstraints(340, 110, 70, -1));

        resetB.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        resetB.setText("Hủy");
        resetB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });
        add(resetB, new AbsoluteConstraints(1160, 100, 100, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void findBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_findBActionPerformed
       
    }//GEN-LAST:event_findBActionPerformed

 
    private void exportFBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exportFBActionPerformed

    }//GEN-LAST:event_exportFBActionPerformed

    private void sortBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sortBtnActionPerformed

    private void namBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_namBActionPerformed

    }//GEN-LAST:event_namBActionPerformed

    private void bothBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_bothBActionPerformed

    }//GEN-LAST:event_bothBActionPerformed

    private void nuBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_nuBActionPerformed

    }//GEN-LAST:event_nuBActionPerformed

    private void resetBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed

    }//GEN-LAST:event_resetBActionPerformed

    private void formComponentResized(ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here: 
    }//GEN-LAST:event_formComponentResized

    private void thFItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_thFItemStateChanged

    }//GEN-LAST:event_thFItemStateChanged

    public JButton getExportFB() {
        return exportFB;
    }

    public JButton getResetB() {
        return resetB;
    }

    public JButton getSortBtn() {
        return sortBtn;
    }

    public JButton getFindB() {
        return findB;
    }

    public JSpinner getMaxF() {
        return maxF;
    }

    public JSpinner getMinF() {
        return minF;
    }

    public JRadioButton getBothB() {
        return bothB;
    }

    public JRadioButton getNamB() {
        return namB;
    }

    public JRadioButton getNuB() {
        return nuB;
    }

    public JComboBox<String> getMonB() {
        return monB;
    }

    public JComboBox<String> getThF() {
        return thF;
    }

    public JTable getTable() {
        return table;
    }

    public JTextField getTimKiemField() {
        return timKiemField;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel SBDLabel;
    private JRadioButton bothB;
    private JButton exportFB;
    private JButton findB;
    private JLabel jLabel11;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JSpinner maxF;
    private JSpinner minF;
    private JComboBox<String> monB;
    private JRadioButton namB;
    private JRadioButton nuB;
    private JButton resetB;
    private JScrollPane scrollBar;
    private JButton sortBtn;
    private JTable table;
    private JComboBox<String> thF;
    private JTextField timKiemField;
    private JLabel title1;
    // End of variables declaration//GEN-END:variables
}
