package views;

import app.Controllers;
import com.toedter.calendar.JDateChooser;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import utilities.others.DateUtils;

public class ThiSinhView extends javax.swing.JPanel {

    /**
     * Creates new form ThiSinhView
     */
    public ThiSinhView() {
        initComponents();
        ngaySinhF.setDateFormatString(DateUtils.formatDateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1 = new javax.swing.JLabel();
        scrollBar = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ngaySinhLabel = new javax.swing.JLabel();
        HoTenLabel = new javax.swing.JLabel();
        tenField = new javax.swing.JTextField();
        gtLabel = new javax.swing.JLabel();
        sbdField = new javax.swing.JTextField();
        tinhLabel = new javax.swing.JLabel();
        truongTHPTLabel = new javax.swing.JLabel();
        sdtLabel = new javax.swing.JLabel();
        sdtField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        ToHopLabel = new javax.swing.JLabel();
        ToanLabel = new javax.swing.JLabel();
        mon1Field = new javax.swing.JTextField();
        batbuocLabel = new javax.swing.JLabel();
        tuChonLabel = new javax.swing.JLabel();
        VanLabel = new javax.swing.JLabel();
        ngoaiNguLabel = new javax.swing.JLabel();
        Mon2Label = new javax.swing.JLabel();
        Mon1Label = new javax.swing.JLabel();
        Mon3Label = new javax.swing.JLabel();
        ChuThichLabel2 = new javax.swing.JLabel();
        ChuThichLabel4 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        toanField = new javax.swing.JTextField();
        mon2Field = new javax.swing.JTextField();
        vanField = new javax.swing.JTextField();
        nnField = new javax.swing.JTextField();
        mon3Field = new javax.swing.JTextField();
        truongF = new javax.swing.JComboBox<>();
        thF = new javax.swing.JComboBox<>();
        ngaySinhF = new com.toedter.calendar.JDateChooser();
        gtF = new javax.swing.JComboBox<>();
        tinhF = new javax.swing.JComboBox<>();
        clearBtn = new javax.swing.JButton();
        SBDLabel1 = new javax.swing.JLabel();
        sortF = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setAutoscrolls(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title1.setText("NHẬP THÔNG TIN THÍ SINH");
        add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 360, -1));

        table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "SBD", "Họ và tên", "Giới tính", "Ngày sinh", "Tỉnh", "Trường", "SĐT", "Khối tổ hợp", "Toán", "Ngữ Văn", "Ngoại ngữ", "Môn 1", "Môn 2", "Môn 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRequestFocusEnabled(false);
        table.setRowHeight(25);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        scrollBar.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        add(scrollBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1210, 360));

        ngaySinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ngaySinhLabel.setText("Ngày sinh");
        add(ngaySinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 70, 30));

        HoTenLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HoTenLabel.setText("Họ và tên");
        add(HoTenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 92, 30));

        tenField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(tenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 210, 30));

        gtLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gtLabel.setText("Giới tính");
        add(gtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 70, 30));

        sbdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(sbdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 140, 30));

        tinhLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tinhLabel.setText("Tỉnh (nơi ở hiện tại)");
        add(tinhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 140, 30));

        truongTHPTLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        truongTHPTLabel.setText("Tên trường THPT");
        add(truongTHPTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 127, 30));

        sdtLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sdtLabel.setText("SĐT");
        add(sdtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 99, 30));

        sdtField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(sdtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 150, 30));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addBtn.setText("ADD");
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 110, -1));

        editBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editBtn.setText("EDIT");
        add(editBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 110, -1));

        delBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delBtn.setText("DELETE");
        add(delBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 100, -1));

        ToHopLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ToHopLabel.setText("Khối tổ hợp môn");
        add(ToHopLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 120, 30));

        ToanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ToanLabel.setText("Toán");
        add(ToanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 49, 30));

        mon1Field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mon1Field.setMaximumSize(new java.awt.Dimension(50, 26));
        mon1Field.setMinimumSize(new java.awt.Dimension(50, 26));
        add(mon1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 70, -1));

        batbuocLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        batbuocLabel.setText("Điểm các môn bắt buộc");
        add(batbuocLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 171, -1));

        tuChonLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tuChonLabel.setText("Điểm các môn tự chọn");
        add(tuChonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 163, -1));

        VanLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VanLabel.setText("Ngữ văn");
        add(VanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 66, 30));

        ngoaiNguLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ngoaiNguLabel.setText("Ngoại ngữ");
        add(ngoaiNguLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, 80, 30));

        Mon2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mon2Label.setText("Môn 2");
        add(Mon2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 50, -1));

        Mon1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mon1Label.setText("Môn 1");
        add(Mon1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, -1, -1));

        Mon3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Mon3Label.setText("Môn 3");
        add(Mon3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 590, -1, 20));

        ChuThichLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChuThichLabel2.setText("KHTN: Môn 1 = Vật lí, Môn 2 = Hoá học, Môn 3 = Sinh học");
        ChuThichLabel2.setToolTipText("");
        ChuThichLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(ChuThichLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 430, -1));

        ChuThichLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChuThichLabel4.setText("KHXH: Môn 1 = Địa lí, Môn 2 = Lịch sử, Môn 3 = GDCD");
        ChuThichLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(ChuThichLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, 430, 20));

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setText("ĐIỀN THÔNG TIN THÍ SINH");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        toanField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toanField.setMaximumSize(new java.awt.Dimension(50, 26));
        toanField.setMinimumSize(new java.awt.Dimension(50, 26));
        add(toanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, 70, -1));

        mon2Field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mon2Field.setMaximumSize(new java.awt.Dimension(50, 26));
        mon2Field.setMinimumSize(new java.awt.Dimension(50, 26));
        add(mon2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 590, 70, -1));

        vanField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vanField.setMaximumSize(new java.awt.Dimension(50, 26));
        vanField.setMinimumSize(new java.awt.Dimension(50, 26));
        add(vanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, 70, 30));

        nnField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nnField.setMaximumSize(new java.awt.Dimension(50, 26));
        nnField.setMinimumSize(new java.awt.Dimension(50, 26));
        add(nnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 520, 70, 30));

        mon3Field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mon3Field.setMaximumSize(new java.awt.Dimension(50, 26));
        mon3Field.setMinimumSize(new java.awt.Dimension(50, 26));
        add(mon3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, 70, -1));
        add(truongF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 220, 30));
        add(thF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 140, 30));
        add(ngaySinhF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 150, 30));

        gtF.setMinimumSize(new java.awt.Dimension(72, 26));
        add(gtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 90, 30));
        add(tinhF, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 220, 30));

        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clearBtn.setText("CLEAR");
        add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 660, 110, -1));

        SBDLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SBDLabel1.setText("SBD");
        add(SBDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 70, 30));

        sortF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sortF.setText("Tự động sắp xếp theo SBD");
        add(sortF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 220, 30));

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 110, 30));
    }// </editor-fold>//GEN-END:initComponents
    

    private void formComponentResized(ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        adjustComponentSizes();
    }//GEN-LAST:event_formComponentResized

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Controllers.ChangePanel("dangNhap");
    }//GEN-LAST:event_jButton1ActionPerformed
    private void adjustComponentSizes() {
        Dimension size = getSize();
        int newWidth = size.width;
        int newHeight = size.height;
        for (Component component : getComponents())
            if (component instanceof JComponent) {
                JComponent jComponent = (JComponent) component;
                Rectangle bounds = jComponent.getBounds();
                jComponent.setBounds(bounds.x, bounds.y, newWidth / 2, bounds.height); // Example resize logic
            }
    }
    
    public JDateChooser getNgaySinhF() {
        return ngaySinhF;
    }
    
    public JTextField getMon3Field() {
        return mon3Field;
    }
    
    public JTextField getMon2Field() {
        return mon2Field;
    }
    
    public JTextField getMon1Field() {
        return mon1Field;
    }
    
    public JTextField getNnField() {
        return nnField;
    }
    
    public JTextField getVanField() {
        return vanField;
    }
    
    public JTextField getToanField() {
        return toanField;
    }
    
    public JTextField getSdtField() {
        return sdtField;
    }
    
    public JTextField getSbdField() {
        return sbdField;
    }
    
    public JTextField getTenField() {
        return tenField;
    }
    
    public JComboBox<String> getTruongF() {
        return truongF;
    }
    
    public JComboBox<String> getTinhF() {
        return tinhF;
    }
    
    public JComboBox<String> getThF() {
        return thF;
    }
    
    public JComboBox<String> getGtF() {
        return gtF;
    }
    
    public JTable getTable() {
        return table;
    }
    
    public JCheckBox getSortF() {
        return sortF;
    }
    
    
    public JButton getEditBtn() {
        return editBtn;
    }
    
    public JButton getDelBtn() {
        return delBtn;
    }
    
    public JButton getClearBtn() {
        return clearBtn;
    }
    
    public JButton getAddBtn() {
        return addBtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChuThichLabel2;
    private javax.swing.JLabel ChuThichLabel4;
    private javax.swing.JLabel HoTenLabel;
    private javax.swing.JLabel Mon1Label;
    private javax.swing.JLabel Mon2Label;
    private javax.swing.JLabel Mon3Label;
    private javax.swing.JLabel SBDLabel1;
    private javax.swing.JLabel ToHopLabel;
    private javax.swing.JLabel ToanLabel;
    private javax.swing.JLabel VanLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel batbuocLabel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox<String> gtF;
    private javax.swing.JLabel gtLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField mon1Field;
    private javax.swing.JTextField mon2Field;
    private javax.swing.JTextField mon3Field;
    private com.toedter.calendar.JDateChooser ngaySinhF;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JLabel ngoaiNguLabel;
    private javax.swing.JTextField nnField;
    private javax.swing.JTextField sbdField;
    private javax.swing.JScrollPane scrollBar;
    private javax.swing.JTextField sdtField;
    private javax.swing.JLabel sdtLabel;
    private javax.swing.JCheckBox sortF;
    private javax.swing.JTable table;
    private javax.swing.JTextField tenField;
    private javax.swing.JComboBox<String> thF;
    private javax.swing.JComboBox<String> tinhF;
    private javax.swing.JLabel tinhLabel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField toanField;
    private javax.swing.JComboBox<String> truongF;
    private javax.swing.JLabel truongTHPTLabel;
    private javax.swing.JLabel tuChonLabel;
    private javax.swing.JTextField vanField;
    // End of variables declaration//GEN-END:variables
}
