/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import entities.GioiTinh;
import entities.ThiSinh;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import views.tabView.*;


public class ThongKeView extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ThongKeView() {
        initComponents();
        tabs.addTab("Phổ điểm", new PhoDiemView());
        tabs.addTab("Số lượng", new SoLuongView());
        tabs.addTab("Khối xét tuyển đại học", new KhoiXetTuyenTK());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jLabel18 = new JLabel();
        minDXHF = new JTextField();
        jLabel19 = new JLabel();
        nuF = new JTextField();
        jLabel20 = new JLabel();
        tongTSF = new JTextField();
        jLabel21 = new JLabel();
        jSeparator3 = new JSeparator();
        jLabel22 = new JLabel();
        jLabel23 = new JLabel();
        jLabel24 = new JLabel();
        jLabel25 = new JLabel();
        jLabel26 = new JLabel();
        jLabel27 = new JLabel();
        namF = new JTextField();
        maxdTNF = new JTextField();
        minDTNF = new JTextField();
        toanTBF = new JTextField();
        jLabel28 = new JLabel();
        jLabel29 = new JLabel();
        maxDXHF = new JTextField();
        jLabel30 = new JLabel();
        vanTBF = new JTextField();
        jLabel31 = new JLabel();
        anhTBF = new JTextField();
        jLabel32 = new JLabel();
        lyTBF = new JTextField();
        jLabel33 = new JLabel();
        hoaTBF = new JTextField();
        jLabel34 = new JLabel();
        sinhTBF = new JTextField();
        jLabel35 = new JLabel();
        suTBF = new JTextField();
        jLabel36 = new JLabel();
        diaTBF = new JTextField();
        jLabel37 = new JLabel();
        gdcdTBF = new JTextField();
        jSeparator5 = new JSeparator();
        jSeparator4 = new JSeparator();
        tabs = new JTabbedPane();
        jLabel2 = new JLabel();

        setLayout(new AbsoluteLayout());

        jLabel1.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        add(jLabel1, new AbsoluteConstraints(1050, 760, -1, -1));

        jPanel1.setLayout(new AbsoluteLayout());

        jLabel18.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Trong đó");
        jPanel1.add(jLabel18, new AbsoluteConstraints(50, 50, 80, 30));

        minDXHF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        minDXHF.setEnabled(false);
        jPanel1.add(minDXHF, new AbsoluteConstraints(220, 320, 80, 30));

        jLabel19.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Nữ");
        jPanel1.add(jLabel19, new AbsoluteConstraints(140, 90, 50, 30));

        nuF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        nuF.setEnabled(false);
        jPanel1.add(nuF, new AbsoluteConstraints(190, 90, 70, 30));

        jLabel20.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("KHXH");
        jPanel1.add(jLabel20, new AbsoluteConstraints(40, 250, 60, 30));

        tongTSF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        tongTSF.setEnabled(false);
        tongTSF.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                tongTSFActionPerformed(evt);
            }
        });
        jPanel1.add(tongTSF, new AbsoluteConstraints(190, 10, 70, 30));

        jLabel21.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Nam");
        jPanel1.add(jLabel21, new AbsoluteConstraints(130, 50, 60, 30));
        jPanel1.add(jSeparator3, new AbsoluteConstraints(10, 360, 310, 10));

        jLabel22.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Tổng số thí sinh");
        jPanel1.add(jLabel22, new AbsoluteConstraints(50, 10, 140, 30));

        jLabel23.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Tổng điểm thấp nhất");
        jPanel1.add(jLabel23, new AbsoluteConstraints(60, 210, 150, 30));

        jLabel24.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Toán");
        jPanel1.add(jLabel24, new AbsoluteConstraints(30, 410, 60, 30));

        jLabel25.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tổng điểm cao nhất");
        jPanel1.add(jLabel25, new AbsoluteConstraints(60, 170, 150, 30));

        jLabel26.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Tổng điểm cao nhất");
        jPanel1.add(jLabel26, new AbsoluteConstraints(60, 280, 150, 30));

        jLabel27.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Tổng điểm thấp nhất");
        jPanel1.add(jLabel27, new AbsoluteConstraints(60, 320, 150, 30));

        namF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        namF.setEnabled(false);
        jPanel1.add(namF, new AbsoluteConstraints(190, 50, 70, 30));

        maxdTNF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        maxdTNF.setEnabled(false);
        jPanel1.add(maxdTNF, new AbsoluteConstraints(220, 170, 80, 30));

        minDTNF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        minDTNF.setEnabled(false);
        jPanel1.add(minDTNF, new AbsoluteConstraints(220, 210, 80, 30));

        toanTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        toanTBF.setEnabled(false);
        jPanel1.add(toanTBF, new AbsoluteConstraints(90, 410, 60, 30));

        jLabel28.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("KHTN");
        jPanel1.add(jLabel28, new AbsoluteConstraints(40, 140, 60, 30));

        jLabel29.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Điểm trung bình từng môn");
        jPanel1.add(jLabel29, new AbsoluteConstraints(50, 370, 230, 30));

        maxDXHF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        maxDXHF.setEnabled(false);
        jPanel1.add(maxDXHF, new AbsoluteConstraints(220, 280, 80, 30));

        jLabel30.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Văn");
        jPanel1.add(jLabel30, new AbsoluteConstraints(30, 450, 60, 30));

        vanTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        vanTBF.setEnabled(false);
        jPanel1.add(vanTBF, new AbsoluteConstraints(90, 450, 60, 30));

        jLabel31.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setText("Anh");
        jPanel1.add(jLabel31, new AbsoluteConstraints(30, 490, 60, 30));

        anhTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        anhTBF.setEnabled(false);
        jPanel1.add(anhTBF, new AbsoluteConstraints(90, 490, 60, 30));

        jLabel32.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Lý");
        jPanel1.add(jLabel32, new AbsoluteConstraints(190, 410, 60, 30));

        lyTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        lyTBF.setEnabled(false);
        jPanel1.add(lyTBF, new AbsoluteConstraints(250, 410, 60, 30));

        jLabel33.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Hóa");
        jPanel1.add(jLabel33, new AbsoluteConstraints(190, 450, 60, 30));

        hoaTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        hoaTBF.setEnabled(false);
        jPanel1.add(hoaTBF, new AbsoluteConstraints(250, 450, 60, 30));

        jLabel34.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Sinh");
        jPanel1.add(jLabel34, new AbsoluteConstraints(190, 490, 60, 30));

        sinhTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        sinhTBF.setEnabled(false);
        jPanel1.add(sinhTBF, new AbsoluteConstraints(250, 490, 60, 30));

        jLabel35.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Sử");
        jPanel1.add(jLabel35, new AbsoluteConstraints(30, 530, 60, 30));

        suTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        suTBF.setEnabled(false);
        jPanel1.add(suTBF, new AbsoluteConstraints(90, 530, 60, 30));

        jLabel36.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Địa");
        jPanel1.add(jLabel36, new AbsoluteConstraints(190, 530, 60, 30));

        diaTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        diaTBF.setEnabled(false);
        jPanel1.add(diaTBF, new AbsoluteConstraints(250, 530, 60, 30));

        jLabel37.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel37.setText("GDCD");
        jPanel1.add(jLabel37, new AbsoluteConstraints(190, 570, 60, 30));

        gdcdTBF.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        gdcdTBF.setEnabled(false);
        jPanel1.add(gdcdTBF, new AbsoluteConstraints(250, 570, 60, 30));
        jPanel1.add(jSeparator5, new AbsoluteConstraints(0, 130, 310, 20));

        jSeparator4.setOrientation(SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new AbsoluteConstraints(340, 0, 10, 750));

        add(jPanel1, new AbsoluteConstraints(0, 60, 340, 610));
        add(tabs, new AbsoluteConstraints(350, 10, 920, 680));

        jLabel2.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("THỐNG KÊ");
        add(jLabel2, new AbsoluteConstraints(70, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tongTSFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongTSFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tongTSFActionPerformed

    public JTabbedPane getTabs() {
        return tabs;
    }

    public JTextField getNuF() {
        return nuF;
    }

    public JTextField getNamF() {
        return namF;
    }

    public JTextField getMinDXHF() {
        return minDXHF;
    }

    public JTextField getMinDTNF() {
        return minDTNF;
    }

    public JTextField getMaxdTNF() {
        return maxdTNF;
    }

    public JTextField getMaxDXHF() {
        return maxDXHF;
    }

    public JTextField getVanTBF() {
        return vanTBF;
    }

    public JTextField getAnhTBF() {
        return anhTBF;
    }

    public JTextField getToanTBF() {
        return toanTBF;
    }

    public JTextField getTongTSF() {
        return tongTSF;
    }

    public JTextField getSinhTBF() {
        return sinhTBF;
    }

    public JTextField getHoaTBF() {
        return hoaTBF;
    }

    public JTextField getLyTBF() {
        return lyTBF;
    }

    public JTextField getGdcdTBF() {
        return gdcdTBF;
    }

    public JTextField getSuTBF() {
        return suTBF;
    }

    public JTextField getDiaTBF() {
        return diaTBF;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField anhTBF;
    private JTextField diaTBF;
    private JTextField gdcdTBF;
    private JTextField hoaTBF;
    private JLabel jLabel1;
    private JLabel jLabel18;
    private JLabel jLabel19;
    private JLabel jLabel2;
    private JLabel jLabel20;
    private JLabel jLabel21;
    private JLabel jLabel22;
    private JLabel jLabel23;
    private JLabel jLabel24;
    private JLabel jLabel25;
    private JLabel jLabel26;
    private JLabel jLabel27;
    private JLabel jLabel28;
    private JLabel jLabel29;
    private JLabel jLabel30;
    private JLabel jLabel31;
    private JLabel jLabel32;
    private JLabel jLabel33;
    private JLabel jLabel34;
    private JLabel jLabel35;
    private JLabel jLabel36;
    private JLabel jLabel37;
    private JPanel jPanel1;
    private JSeparator jSeparator3;
    private JSeparator jSeparator4;
    private JSeparator jSeparator5;
    private JTextField lyTBF;
    private JTextField maxDXHF;
    private JTextField maxdTNF;
    private JTextField minDTNF;
    private JTextField minDXHF;
    private JTextField namF;
    private JTextField nuF;
    private JTextField sinhTBF;
    private JTextField suTBF;
    private JTabbedPane tabs;
    private JTextField toanTBF;
    private JTextField tongTSF;
    private JTextField vanTBF;
    // End of variables declaration//GEN-END:variables
}
