/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.tabView;

import entities.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.*;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import utilities.ui.Ui;

public class SoLuongView extends javax.swing.JPanel {

    /**
     * Creates new form SoLuongView
     */
    public SoLuongView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tinhG = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        truongG = new javax.swing.JPanel();
        tinhF = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1000, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Thống kê số lượng thí sinh của từng tỉnh");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        tinhG.setPreferredSize(new java.awt.Dimension(900, 250));

        javax.swing.GroupLayout tinhGLayout = new javax.swing.GroupLayout(tinhG);
        tinhG.setLayout(tinhGLayout);
        tinhGLayout.setHorizontalGroup(
            tinhGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        tinhGLayout.setVerticalGroup(
            tinhGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        add(tinhG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 850, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 760, 90, 40));

        truongG.setPreferredSize(new java.awt.Dimension(900, 250));

        javax.swing.GroupLayout truongGLayout = new javax.swing.GroupLayout(truongG);
        truongG.setLayout(truongGLayout);
        truongGLayout.setHorizontalGroup(
            truongGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        truongGLayout.setVerticalGroup(
            truongGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        add(truongG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 850, -1));

        tinhF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tinhFItemStateChanged(evt);
            }
        });
        add(tinhF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Thống kê số lượng thí sinh của từng trường trong tỉnh");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 480, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Chọn tỉnh");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tinhFItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_tinhFItemStateChanged
        // TODO add your handling code here:
        veTruongGraph();
    }//GEN-LAST:event_tinhFItemStateChanged
    
    void veTinhGraph() {
//                if (tkeComboBox.getSelectedIndex() != 1) return;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        List<GioiTinh> gt = GioiTinh.getDB().QUERY();
        for (TinhThanh tt : TinhThanh.getDB().QUERY()) {
            List<ThiSinh> ts = ThiSinh.getDB().QUERY(i -> i.getTruong().getTinh().equals(tt));
            dataset.addValue(ts.size(), "TỔNG", tt.getID());
            dataset.addValue(ts.stream().filter(i -> i.getGioiTinh().equals(gt.get(0))).count(), "NAM", tt.getID());
            dataset.addValue(ts.stream().filter(i -> i.getGioiTinh().equals(gt.get(1))).count(), "NỮ", tt.getID());
        }
        
        JFreeChart lineChart = ChartFactory.createBarChart(
                "Biểu đồ thống kê thí sinh theo tỉnh",
                "Tỉnh",
                "Số thí sinh",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, true
        );
        Ui.displayGraph(tinhG, new ChartPanel(lineChart));
    }
    
    void veTruongGraph() {
        if (tinhF.getSelectedItem() == null) updateTinhF();
        
        TinhThanh tinh = TinhThanh.getDB().QUERY_ID((String) tinhF.getSelectedItem());
        List<TruongHoc> truong = TruongHoc.getDB().QUERY(i -> i.getTinh().equals(tinh));
        List<GioiTinh> gt = GioiTinh.getDB().QUERY();
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (TruongHoc tr : truong) {
            List<ThiSinh> ts = ThiSinh.getDB().QUERY(i -> i.getTruong().equals(tr));
            dataset.addValue(ts.size(), "TỔNG", tr.getTenTruong());
            dataset.addValue(ts.stream().filter(i -> i.getGioiTinh().equals(gt.get(0))).count(), "NAM", tr.getTenTruong());
            dataset.addValue(ts.stream().filter(i -> i.getGioiTinh().equals(gt.get(1))).count(), "NỮ", tr.getTenTruong());
        }
        
        JFreeChart lineChart = ChartFactory.createBarChart(
                "Biểu đồ thống kê thí sinh theo trường của tỉnh " + tinh.getID(),
                "Trường",
                "Số thí sinh",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, true
        );
        Ui.displayGraph(truongG, new ChartPanel(lineChart));
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody

        if (!aFlag) return;
        updateTinhF();
        veTinhGraph();
        veTruongGraph();
    }
    
    void updateTinhF() {
        Ui.updateComboBox(tinhF, TinhThanh.getDB().MAP(i -> i.getID()).toList());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> tinhF;
    private javax.swing.JPanel tinhG;
    private javax.swing.JPanel truongG;
    // End of variables declaration//GEN-END:variables
}
